baseurl = "https://www.cocooei.com/"
title = "Coco Oei"
author = "Coco Oei"
canonifyurls = true
languagecode = "en"
theme = "black-and-light"

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "Coco Oei"
  disableWebFonts = false

[[menu.main]]
    name = "About"
    url  = "https://cocooei.com/about"
[[menu.main]]
    name = "Vimeo"
    url  = "https://vimeo.com/cocooei"
[[menu.main]]
    name = "Soundcloud"
    url  = "https://soundcloud.com/moodyteenager"
